spring:
  datasource:
    url: jdbc:h2:mem:test-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      
  jackson:
    property-naming-strategy: SNAKE_CASE